version: '3.0'
services:
  pg:
    container_name: postgres_api_video
    image: postgres
    ports: 
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: secure
  rails:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api_video
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - pg
    environment:
      PG_PASSWORD: secure 
      PG_USER: postgres
      PG_HOST: postgres_api_video